export { default as Login } from './Login'
export { default as ContenidoA } from './ContenidoA'
export { default as Menu } from './Menu'
export { default as AlumonosAgregar } from './AlumnosAgregar'
export { default as AlumnosConsultar } from './AlumnosConsultar'
export { default as AlumnosModificar } from './AlumnoModificar'
export { default as AlumnoEliminar } from './AlumnoEliminar'
